name: Deploy

on:
    workflow_dispatch:
    push:
        branches:
            - master
            - vuepress-v2
    pull_request:
        branches:
            - master
            - vuepress-v2

permissions:
    contents: write
    actions: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  # 如果你文档需要 Git 子模块，取消注释下一行
                  # submodules: true

            - name: 安装 pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8.2.0
                  run_install: true

            - name: 设置 Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: pnpm

            - name: 构建文档
              env:
                  NODE_OPTIONS: --max_old_space_size=8192
                  #   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  GITHUB_TOKEN: ${{secrets.TOKEN_GITHUB}}
              run: |-
                  pnpm run deploy

            - name: Sync to Gitee
              uses: wearerequired/git-mirror-action@master
              env:
                  # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
              with:
                  # 注意替换为你的 GitHub 源仓库地址
                  source-repo: git@github.com:lxchuan12/lxchuan12.github.io.git
                  # 注意替换为你的 Gitee 目标仓库地址
                  destination-repo: git@gitee.com:lxchuan12/lxchuan12.git

            - name: Build Gitee Pages
              uses: yanglbme/gitee-pages-action@main
              with:
                  # 注意替换为你的 Gitee 用户名
                  gitee-username: lxchuan12
                  # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
                  gitee-password: ${{ secrets.GITEE_PASSWORD }}
                  # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
                  gitee-repo: lxchuan12
                  # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
                  branch: master
